@startuml

actor       ユーザー      as a1
boundary    ホーム画面    as b1
boundary    一つ前の質問画面    as b2
boundary    一つ後の質問画面    as b3
boundary    過去の質問画面    as b4
boundary    候補者ページ画面    as b5
boundary    つぶやき画面    as b6
boundary    質問と返答画面    as b7


control     候補者ページを表示し   as c1
control     つぶやき表示    as c2
control     質問と返答表示  as c3

entity      質問と返答のデータ     as e1



a1 -> b1 :1. 候補者クリックをする 
b1 -> c1 :1.1起動()
c1 --> b5 :1.1.1表示()
a1 -> b5 :2.「つぶやき」を押す
b5 -> c2 :2.1起動()
c2 --> b6 :2.1.1表示()
a1->b6:3.画面下部までスクロール
b6-> c3 :3.1起動()
c3-->b7:3.1.2表示()
a1 -> b7 :4.◀ボタンを押す

b7->c3:4.1起動()
e1->c3:4.2起動()
c3-->b2:4.1.1表示()
a1 -> b7 :5.▶ボタンを押す

b7->c3:5.1起動()
e1->c3:6起動()
c3-->b3:6.1表示()

a1 -> b7 :7.「過去の質問を見る」を押す
b7->c3:7.1起動()
e1->c3:8.起動()
c3-->b4:8.1表示()









@enduml
